title: The Book
description: The Engineering Book
email: work.sangwoo.joh@gmail.com
author: Sangwoo Joh

repo: "https://github.com/sangwoo-joh/the-book"
github_user: "sangwoo-joh"
github_repo: "the-book"
github_branch: "master"

version_params:
  allow_search: true
  search_versions:
    - Previous
  latest: Current
  versions:
    - Current
    - Previous

google-analytics: G-63ZZVFHP73
logo: "assets/img/logo.png"
logo_pixels: 34
color: "#483D8B"
markdown: kramdown
tag_color: primary # danger, success, warning, primary, info, secondary
accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: pretty
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: true
  profile: false
